### ISSUE TITLE
Initial training task - daily mean, standard deviation, and samples

### ISSUE THREAD

**Issue by DaniJonesOcean** [CIGLR-ai-lab/GreatLakes-TempSensors#21]
**Description:**
Here we aim to carry out an initial training task using GLSEA3 data to train DeepSensor to target the temperature distribution at all grid cells. After the fit is done, we want to create visualizations for the mean DeepSensor prediction, its standard deviation, and sample representations from the distribution of Great Lakes surface temperature measurements. 

**Goals:**
- [ ] Train DeepSensor using daily GLSEA3 data, with all water points as context and target points.
- [ ] Plot the daily mean surface temperature as estimated by DeepSensor .
- [ ] Plot the daily standard deviation of surface temperature (i.e. the prediction error).
- [ ] Generate samples from the surface temperature distribution and plot them.

**Steps:**
1. Begin by loading the dataset and preprocess it using the data processor provided by DeepSensor.
2. Train the `ConvNP` model from DeepSensor, giving us a probabilistic distribution of temperature.
3. Develop plots that clearly represent daily mean and standard deviation over a given time period.
4. Generate random samples from the temperature distribution and add them to our visualizations.
5. Ensure all visualizations are clear, well-labeled, and include a legend where appropriate.

**Expected Outcome:**
By the end of this task, we should have a set of visualizations that accurately portrays daily variations in surface temperature, as well as the inherent uncertainty and variability of the data as captured by our trained DeepSensor model and sampled points.

**Additional Context:**
Visualizations will significantly aid in answering our overarching research question, “Where should the next generation of temperature measurement sensors be placed in order to most efficiently improve our quantitative understanding of Great Lakes surface temperature variability?”

**Comment by eredding02** [comment]
@DaniJonesOcean Here are plots from a 06-29-2016 predictive task.

![Image](https://github.com/user-attachments/assets/10493c23-c25a-433c-9a12-c826a3e01991)
